In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:

x = list(range(10, 51))
np.array(x)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:

x = list(range(10, 51,2))
np.array(x)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(3, 3)
print(newarr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
np.eye(3, k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
from numpy import random
x = random.rand()
x

0.8613516089722628

In [10]:
x = random.randn(25)
x

array([-0.75534399, -0.93087149, -1.51115464, -0.57285731,  0.2093529 ,
       -1.05761087, -0.2141694 ,  0.71377661, -0.02052408,  3.44344067,
        0.17148979,  1.48234044,  0.80794702,  1.47680268,  0.40682225,
       -0.18938546,  0.10347391,  0.38670003, -0.49680704,  1.15980777,
        1.28610684, -0.115015  , -0.12126356, -0.04134015, -1.43049078])

In [11]:
x = np.arange(0.01,1.01,0.01).reshape(10,10)
x

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [12]:
np.linspace(0,1,num=20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
x = mat[2:,1:]
x

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [15]:
x[1,3]

20

In [16]:
y = mat[:3,1:2]
y

array([[ 2],
       [ 7],
       [12]])

In [17]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [18]:
z = mat[3:5]
z

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
sum = 0;
for x in np.nditer(mat):
    sum += x

print(sum)

325


In [20]:
mat.sum()

325

In [21]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [22]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:, 1:4])

[[2 3 4]
 [7 8 9]]


In [23]:
import pandas as pd
import numpy as np
index=['falcon', 'parrot', 'lion', 'monkey']
columns=['class', 'max_speed']
df = pd.DataFrame([('bird', 389.0),
                   ('bird', 24.0),
                   ('mammal', 80.5),
                   ('mammal', np.nan)],index,columns)

df

class  max_speed
falcon    bird      389.0
parrot    bird       24.0
lion    mammal       80.5
monkey  mammal        NaN

In [24]:
df.reset_index()

index   class  max_speed
0  falcon    bird      389.0
1  parrot    bird       24.0
2    lion  mammal       80.5
3  monkey  mammal        NaN

In [25]:
df.reset_index(drop=True)

class  max_speed
0    bird      389.0
1    bird       24.0
2  mammal       80.5
3  mammal        NaN

In [26]:
names=['class', 'name']

In [27]:
a = ("John", "Charles", "Mike")
b = ("Jenny", "Christy", "Monica")

x = list(zip(a, b))
x


[('John', 'Jenny'), ('Charles', 'Christy'), ('Mike', 'Monica')]