In [ ]:
def caught_speeding(speed, is_birthday):
    if is_birthday == True:
        if 0 <= speed and speed <= 65:
            print("No ticket")
        elif 66 <= speed and speed <= 85:
            print("Small ticket")
        else:
            print("Big Ticket")
    else:
        if 0 <= speed and speed <= 60:
            print("No ticket")
        elif 61 <= speed and speed <= 80:
            print("Small ticket")
        else:
            print("Big Ticket")

In [ ]:
caught_speeding(81,False)

Big Ticket


Set items are unordered, unchangeable, and do not allow duplicate values.

In [ ]:
myset = {"apple", "banana", "cherry"}
print(myset)

{'cherry', 'banana', 'apple'}


In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [4]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [14]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8


In [15]:

import numpy as np
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [16]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [17]:
from numpy import random

x = random.randint(100)

print(x)


21


In [22]:

np.arange(3,7)

array([3, 4, 5, 6])

In [21]:
np.arange(3,7,2)

array([3, 5])

In [25]:

np.zeros(2, dtype=int)


array([0, 0])

In [27]:
np.linspace(2.0, 3.0, num=7)

array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333, 3.        ])

In [31]:
np.eye(4, k=0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.random.rand(3)

array([0.95236026, 0.07254246, 0.43902271])

In [34]:
x = np.random.randn(3)

In [37]:
x

array([-1.81239155,  0.87344687, -0.3735314 ])

In [38]:
x.max()

0.8734468666855204

In [39]:
x.min()

-1.8123915510611197

In [40]:
x.argmax()

1

In [41]:
x.argmin()

0

In [42]:
arr[:] = 88

In [43]:
from numpy import random
x = random.randn(3, 4)
print(x)

[[ 0.07541315  0.17066792  1.33333785 -0.38471761]
 [-0.11697159  0.87558846 -1.54535226  0.16783434]
 [-0.21988817  0.57780501  0.49977995  1.4971876 ]]


In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [58]:
Import NumPy as np

SyntaxError: ignored

In [59]:
import NumPy as np

ModuleNotFoundError: ignored

4