In [16]:
pip install numpy


[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


NumPy is a Python library.

*`NumPy is used for working with arrays.`*

NumPy is short for "Numerical Python".



**The array object in NumPy is called ndarray,** it provides a lot of supporting functions that make working with ndarray very easy.

Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

**We can create a NumPy ndarray object by using the array() function.**



In [17]:
#To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

import numpy as np

mylist = [1, 2, 3, 4, 5]
arr = np.array(mylist)
print(mylist)          #[1, 2, 3, 4, 5]
print(arr)             #[1 2 3 4 5]
print(arr.sum())       #15
print(np.__version__)  #1.23.5
print(type(arr))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
15
2.0.0
<class 'numpy.ndarray'>


In [18]:
arr = np.array([4215])
print(arr)

[4215]


In [19]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [20]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [21]:
# Higher Dimensional Arrays
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [29]:
arr.T

array([[[[[1]]]],



       [[[[2]]]],



       [[[[3]]]],



       [[[[4]]]]])

In [35]:
v1 = np.array([1,2,3])

In [53]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [94]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2,6,1)
print(newarr)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]]]


In [108]:
# Create two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

a = np.matmul(A,B)
a


array([[19, 22],
       [43, 50]])

In [110]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [111]:
# Dot product
f = np.matmul(a, b)
print(f)

32


In [113]:
# Transpose of a matrix
A = np.array([[1, 2], [3, 4]])
D = np.transpose(A)
print(D)


[[1 3]
 [2 4]]
