In [151]:
# NumPy is used for working with arrays.
# The array object in NumPy is called ndarray.

# We can create a NumPy ndarray object by using the array() function.

In [152]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [153]:
import numpy as np

In [154]:
mylist = [1, 2, 3, 4, 5]     #1 dimesntion array
arr = np.array(mylist)

print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [155]:
mytuple = (1, 2, 3, 4, 5)
arr = np.array((1, 2, 3, 4, 5))

print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [156]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e = np.array([[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]],[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
4


In [157]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(e.shape)

()
(5,)
(2, 3)
(2, 2, 3)
(2, 2, 2, 3)


In [158]:
newarr = d.reshape(4, 3)
newarr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [159]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [160]:
d[1][0][1]

2

In [161]:
d[1,0,1]

2

In [162]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [163]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [164]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [165]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [166]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [167]:
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8


Join Array and split

In [168]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
arr


array([1, 2, 3, 4, 5, 6])

In [169]:
newarr = np.hsplit(arr,2)
# newarr = np.array_split(arr,2)
newarr

[array([1, 2, 3]), array([4, 5, 6])]

In [170]:
# Join two 2-D arrays along rows (axis=1):

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [171]:
newarr = np.hsplit(arr,2)
newarr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [172]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
# arr = np.concatenate((arr1, arr2), axis=1)  # axis 1 is out of bounds for array of dimension 1
print(arr)
print(arr.ndim)

[[1 4]
 [2 5]
 [3 6]]
2


In [173]:
newarr = np.hsplit(arr,1)
newarr

[array([[1, 4],
        [2, 5],
        [3, 6]])]

In [174]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
arr_new = np.concatenate((arr1, arr2))
print(arr)
print(arr_new)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [175]:
newarr = np.hsplit(arr,2)
newarr

[array([1, 2, 3]), array([4, 5, 6])]

In [176]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [177]:
newarr = np.vsplit(arr,2)
newarr

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [178]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [179]:
newarr = np.array_split(arr,1,axis=1)
newarr


[array([[[1, 4],
         [2, 5],
         [3, 6]]])]