In [2]:
# NumPy is used for working with arrays.
# The array object in NumPy is called ndarray.

# We can create a NumPy ndarray object by using the array() function.

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [5]:
mylist = [1, 2, 3, 4, 5]     #1 dimesntion array
arr = np.array(mylist)

print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [6]:
mytuple = (1, 2, 3, 4, 5)
arr = np.array((1, 2, 3, 4, 5))

print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [7]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e = np.array([[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]],[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
4


In [8]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [9]:
d[1][0][1]

2

In [10]:
d[1,0,1]

2

In [13]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [16]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [17]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [18]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]
